### ISSUE TITLE
Update Cake.Gitter to target Cake v1.0.0

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.Gitter#45]
https://cakebuild.net/blog/2021/02/cake-v1.0.0-released

**Comment by gep13** [comment]
@augustoproiete this was rebased and merged in here: https://github.com/cake-contrib/Cake.Gitter/commit/6c442534346146890b27034fa01c54237441453a

**Comment by gep13** [comment]
@augustoproiete thanks for getting this updated!
